"""Add additional info for item number and description

Revision ID: 163b773b7f5d
Revises: 56f325841de6
Create Date: 2025-03-08 12:11:28.284703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '163b773b7f5d'
down_revision = '56f325841de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sale_qty', sa.Integer(), nullable=False),
    sa.Column('discount_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('item_no', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('product_brand_id', sa.UUID(), nullable=False),
    sa.Column('product_group_id', sa.UUID(), nullable=False),
    sa.Column('product_division_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_brand_id'], ['product_brands.uuid'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.uuid'], ),
    sa.ForeignKeyConstraint(['product_division_id'], ['product_divisions.uuid'], ),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('product_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_info',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_no', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name='product_info_pkey')
    )
    op.drop_table('sales')
    # ### end Alembic commands ###
