"""Create sales table

Revision ID: 56f325841de6
Revises: af2110dbc8c4
Create Date: 2025-03-08 11:57:11.465270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f325841de6'
down_revision = 'af2110dbc8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sale_qty', sa.Integer(), nullable=False),
    sa.Column('discount_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('product_brand_id', sa.UUID(), nullable=False),
    sa.Column('product_group_id', sa.UUID(), nullable=False),
    sa.Column('product_division_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('product_info_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_brand_id'], ['product_brands.uuid'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.uuid'], ),
    sa.ForeignKeyConstraint(['product_division_id'], ['product_divisions.uuid'], ),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.uuid'], ),
    sa.ForeignKeyConstraint(['product_info_id'], ['product_info.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
