"""Temp_import adjust for incremental upload

Revision ID: 8f309350115f
Revises: 3644ad1b0cb5
Create Date: 2025-04-23 22:24:59.752826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f309350115f'
down_revision = '3644ad1b0cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_imports', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('progress')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
