"""Create tax configuration table

Revision ID: aa080a9ef992
Revises: c3cc5005e693
Create Date: 2025-04-02 17:32:02.793016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa080a9ef992'
down_revision = 'ad9537e6141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_configurations',
                    sa.Column('uuid', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('tax_rate', sa.Numeric(
                        precision=5, scale=2), nullable=False),
                    sa.Column('effective_from', sa.Date(), nullable=False),
                    sa.Column('effective_until', sa.Date(), nullable=True),
                    sa.Column('description', sa.String(
                        length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('uuid')
                    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounted_amt', sa.Numeric(
            precision=10, scale=2), nullable=False))
        batch_op.drop_column('discount_amt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amt', sa.NUMERIC(
            precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('discounted_amt')

    op.drop_table('tax_configurations')
    # ### end Alembic commands ###
