"""empty message

Revision ID: c3cc5005e693
Revises: ad9537e6141c
Create Date: 2025-03-09 13:43:06.510517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cc5005e693'
down_revision = 'ad9537e6141c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_brands',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_divisions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_groups',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sales',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('sale_qty', sa.Integer(), nullable=False),
    sa.Column('discount_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_amt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('item_no', sa.String(length=50), nullable=True),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('product_brand_id', sa.UUID(), nullable=False),
    sa.Column('product_group_id', sa.UUID(), nullable=False),
    sa.Column('product_division_id', sa.UUID(), nullable=False),
    sa.Column('product_category_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_brand_id'], ['product_brands.uuid'], ),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.uuid'], ),
    sa.ForeignKeyConstraint(['product_division_id'], ['product_divisions.uuid'], ),
    sa.ForeignKeyConstraint(['product_group_id'], ['product_groups.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('product_groups')
    op.drop_table('product_divisions')
    op.drop_table('product_categories')
    op.drop_table('product_brands')
    # ### end Alembic commands ###
