version: "3.8"

services:
  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./flask-backend/.env
    depends_on:
      - db
    networks:
      - recipe_app_network

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./react-frontend/.env
    networks:
      - recipe_app_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - recipe_app_network

volumes:
  postgres_data:

networks:
  recipe_app_network:
    driver: bridge
