version: "3.8"

services:
  backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./flask-backend/.env
    depends_on:
      - db
    networks:
      - savory_script_network

  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    volumes:
      - ./react-frontend/build:/app/savory-script/build
    ports:
      - "5000:5000"
    networks:
      - savory_script_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - savory_script_network
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    external: true

networks:
  savory_script_network:
    driver: bridge
