FROM node:20 as build

RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -
ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
RUN pnpm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html/savoryscript
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]