FROM node:20

RUN curl -fsSL https://get.pnpm.io/install.sh | SHELL="$(which bash)" bash -

ENV PATH="/root/.local/share/pnpm:$PATH"

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm run build

RUN npm install -g serve

EXPOSE 5000

CMD ["serve", "-s", "build", "-l", "5000"]